### PR TITLE
Deluxe spinning action

### PR DESCRIPTION
**Pull request by nickserv**
Notes:
- The spinning will not stop until you reload the page or load another one. I feel like we shouldn't implement a feature to disable it, since it's not really needed.
- ~~This will affect ALL `<i>` tags across the site. This shouldn't be an issue, since all that's happening is a CSS class being added on, but we might want to eventually change this so it only looks for `<i>` tags that are actually being used for icons (via jQuery selectors with regex or something like that).~~ Fixed.
- ~~This doesn't make any images besides icons spin. I should probably fix this eventually.~~ Fixed.

### CODE REVIEW

**Comment by kristenmills** [comment]
There is no gif. FIX IT

**Comment by nickserv** [comment]
Fixed, and added another bullet to the notes.

**Comment by nickserv** [comment]
It seems like I fixed all the issues with this. This is pretty ready to be merged now.

**Comment by nickserv** [comment]
So, who thinks we should merge this (besides me)?

**Comment by kristenmills** [comment]
I vote yes

**Pull request merged**
